server:
    port: 0
spring:
  application:
    name: user-microservice
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DBNAME:meal-org}
      username: ${MONGODB_USER:admin}
      password: ${MONGODB_PASSWORD:admin}

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.0.1:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${random.uuid}