server:
  port: 6666
spring:
  application:
    name: meal-microservice
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DBNAME:meal-organizer-data}
      #username: ${MONGODB_USER:admin}
      #password: ${MONGODB_PASSWORD:admin}

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: ${HOST_IP:localhost}
    instanceId: ${spring.application.name}:${random.uuid}