server:
  port: 4445

  spring:
    data:
      mongodb:
        uri: mongodb://localhost:27017/meal-org
        #host: mongodb
        #port: 27017
        #database: meal-org
        #authentication-database: admin
        #username: admin
        #password: admin