server:
    port: 4445
spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DBNAME:meal-org}
      username: ${MONGODB_USER:admin}
      password: ${MONGODB_PASSWORD:admin}
